/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ac1pokemons;

import javax.swing.JTextField;

/**
 *
 * @author Samsung
 */
public class EscolherPokemons extends javax.swing.JFrame {

    /**
     * Creates new form EscolherPokemons
     */
    public EscolherPokemons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PicsCharmander = new javax.swing.JLabel();
        CampoTexto = new javax.swing.JTextField();
        BotonBatalhar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PicsBulbasaur = new javax.swing.JLabel();
        PicsSquirtle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(398, 298));
        setPreferredSize(new java.awt.Dimension(398, 298));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Charmander");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 86, 17);

        PicsCharmander.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ac1pokemons/Pics/charmander.png"))); // NOI18N
        getContentPane().add(PicsCharmander);
        PicsCharmander.setBounds(20, 60, 64, 64);

        CampoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoTextoActionPerformed(evt);
            }
        });
        getContentPane().add(CampoTexto);
        CampoTexto.setBounds(80, 190, 214, 20);

        BotonBatalhar.setBackground(new java.awt.Color(102, 204, 255));
        BotonBatalhar.setText("Batalhar");
        BotonBatalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBatalharActionPerformed(evt);
            }
        });
        getContentPane().add(BotonBatalhar);
        BotonBatalhar.setBounds(150, 220, 73, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Bulbasaur");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 40, 69, 17);

        PicsBulbasaur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ac1pokemons/Pics/bulbasaur.png"))); // NOI18N
        getContentPane().add(PicsBulbasaur);
        PicsBulbasaur.setBounds(150, 50, 96, 79);

        PicsSquirtle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ac1pokemons/Pics/squirtle.png"))); // NOI18N
        getContentPane().add(PicsSquirtle);
        PicsSquirtle.setBounds(260, 60, 84, 51);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Squirtle");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(280, 40, 53, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Digite 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 90, 22);

        jLabel5.setBackground(new java.awt.Color(0, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText("Digite 2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 130, 80, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Digite 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 130, 80, 22);

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ac1pokemons/Pics/fondos-escritorio-pokemon-p.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 400, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CampoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoTextoActionPerformed
        CampoTexto.getText();
    }//GEN-LAST:event_CampoTextoActionPerformed

    private void BotonBatalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBatalharActionPerformed
        int escolha;
        escolha = Integer.parseInt(CampoTexto.getText());
        
        
        pokemons MyPokemon = null;

        switch(escolha){
             case 1:  
             Lutar newlutar = new Lutar();
             newlutar.setVisible(true);
             dispose();
             
             break;
             case 2: pokemons MyPokemon2 = new pokemons("Bulbasaur", "Planta", 1);
             MyPokemon = MyPokemon2;
             
             Lutar2 newlutar2 = new Lutar2();
             newlutar2.setVisible(true);
             dispose();
             break;
             case 3:  pokemons MyPokemon3 = new pokemons("Squirtle", "Agua", 1);
             MyPokemon = MyPokemon3;
             
             Lutar3 newlutar3 = new Lutar3();
             newlutar3.setVisible(true);
             dispose();
             break;
         
         }
    }//GEN-LAST:event_BotonBatalharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherPokemons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherPokemons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBatalhar;
    private javax.swing.JTextField CampoTexto;
    private javax.swing.JLabel PicsBulbasaur;
    private javax.swing.JLabel PicsCharmander;
    private javax.swing.JLabel PicsSquirtle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    private int parseInt(JTextField CampoTexto) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
